/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.cytoscape.pesca.internal;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JFrame;
import org.cytoscape.application.swing.CytoPanelComponent;
import org.cytoscape.application.swing.CytoPanelName;
import org.cytoscape.model.CyNetwork;
import org.cytoscape.model.CyNode;
import org.cytoscape.model.CyTableUtil;

/**
 *
 * @author scardoni
 */
public class PescaIsolatedWindows extends  JFrame implements CytoPanelComponent {

    /**
     * Creates new form Pescaconncetedisolatedwindows
     */
    CyNetwork network;
    PescaStartMenu pescastartmenu;
    
    public PescaIsolatedWindows(CyNetwork network, PescaStartMenu pescastartmenu) {
        this.network = network;
        this.pescastartmenu = pescastartmenu;
        initComponents();
        jButtonNodesOk.setEnabled(false);
        jButtonStart.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IsolatedCompPanel = new javax.swing.JPanel();
        jLabelSelectGiant = new javax.swing.JLabel();
        jButtonGiantOk = new javax.swing.JButton();
        jLabelSelectNodes = new javax.swing.JLabel();
        jLabelSelectNodes2 = new javax.swing.JLabel();
        jButtonNodesOk = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelStart = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelGiantLoaded = new javax.swing.JLabel();
        jLabelNodesLoaded = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSelectGiant.setText("Select the giant component and click 'Giant OK' button");

        jButtonGiantOk.setText("Giant OK");
        jButtonGiantOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGiantOkActionPerformed(evt);
            }
        });

        jLabelSelectNodes.setText("Select one or more nodes to be connected to the Giant Component ");

        jLabelSelectNodes2.setText("and click 'Nodes OK' Button");

        jButtonNodesOk.setText("Nodes OK");
        jButtonNodesOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNodesOkMouseClicked(evt);
            }
        });
        jButtonNodesOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNodesOkActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(204, 0, 51));
        jLabelTitle.setText("Pesca: Connecting isolated nodes to a Giant component");

        jLabelStart.setText("Now click on 'Start' to start computation or click on Cancel to go back to start menu");

        jButtonStart.setText("Ok");
        jButtonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStartMouseClicked(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        jLabelGiantLoaded.setForeground(new java.awt.Color(204, 0, 0));
        jLabelGiantLoaded.setText("Giant Component not loaded");
        jLabelGiantLoaded.setToolTipText("");

        jLabelNodesLoaded.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNodesLoaded.setText("List of nodes not loaded");

        javax.swing.GroupLayout IsolatedCompPanelLayout = new javax.swing.GroupLayout(IsolatedCompPanel);
        IsolatedCompPanel.setLayout(IsolatedCompPanelLayout);
        IsolatedCompPanelLayout.setHorizontalGroup(
            IsolatedCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsolatedCompPanelLayout.createSequentialGroup()
                .addGroup(IsolatedCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsolatedCompPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(IsolatedCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsolatedCompPanelLayout.createSequentialGroup()
                                .addComponent(jButtonGiantOk, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelGiantLoaded))
                            .addGroup(IsolatedCompPanelLayout.createSequentialGroup()
                                .addGroup(IsolatedCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSelectNodes2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSelectGiant, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSelectNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStart))
                                .addGap(0, 91, Short.MAX_VALUE))
                            .addGroup(IsolatedCompPanelLayout.createSequentialGroup()
                                .addComponent(jButtonNodesOk, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNodesLoaded)
                                .addGap(29, 29, 29))))
                    .addGroup(IsolatedCompPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitle))
                    .addGroup(IsolatedCompPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        IsolatedCompPanelLayout.setVerticalGroup(
            IsolatedCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsolatedCompPanelLayout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabelSelectGiant, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(IsolatedCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGiantOk)
                    .addComponent(jLabelGiantLoaded, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabelSelectNodes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSelectNodes2)
                .addGap(18, 18, 18)
                .addGroup(IsolatedCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNodesOk)
                    .addComponent(jLabelNodesLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabelStart, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IsolatedCompPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IsolatedCompPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IsolatedCompPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNodesOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNodesOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNodesOkActionPerformed

    private void jButtonGiantOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGiantOkActionPerformed
       
// TODO add your handling code here:
List<CyNode> listaGiant = CyTableUtil.getNodesInState(network,"selected",true);
System.out.println("lista nodi = " + listaGiant.toString());
pescastartmenu.GiantComponent = listaGiant;
this.jLabelGiantLoaded.setText("OK! Giant Component loaded!");
this.jLabelGiantLoaded.setForeground(Color.green);
this.jButtonGiantOk.setEnabled(false);
this.jButtonNodesOk.setEnabled(true);

    }//GEN-LAST:event_jButtonGiantOkActionPerformed

    private void jButtonNodesOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNodesOkMouseClicked
        // TODO add your handling code here:
        List<CyNode> listaNodestoConnect = CyTableUtil.getNodesInState(network,"selected",true);
        System.out.println("lista nodi = " + listaNodestoConnect.toString());
pescastartmenu.NodestoConnect = listaNodestoConnect;
this.jLabelNodesLoaded.setText("OK! Nodes to be connected loaded!");
this.jLabelNodesLoaded.setForeground(Color.green);
this.jButtonNodesOk.setEnabled(false);
this.jButtonStart.setEnabled(true);
        
        
    }//GEN-LAST:event_jButtonNodesOkMouseClicked

    private void jButtonStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStartMouseClicked
pescastartmenu.startcomputation();
this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStartMouseClicked
public Icon getIcon() {
		return null;
	}
public String getTitle() {
		return "Pesca";
	}
public CytoPanelName getCytoPanelName() {
		return CytoPanelName.WEST;
	}
  public Component getComponent() {
		return this;
	}

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelMouseClicked

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PescaIsolatedWindows(network).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IsolatedCompPanel;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonGiantOk;
    private javax.swing.JButton jButtonNodesOk;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabelGiantLoaded;
    private javax.swing.JLabel jLabelNodesLoaded;
    private javax.swing.JLabel jLabelSelectGiant;
    private javax.swing.JLabel jLabelSelectNodes;
    private javax.swing.JLabel jLabelSelectNodes2;
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
